name: Pipelines
run-name: Drift Detection
on:
  workflow_call:
    inputs:
      # This field can be overriden to customize the runner used for pipelines
      # workflows.
      #
      # IMPORTANT: To use self-hosted runners this workflow must be hosted in
      # the same GitHub organization as your infra-live repository.
      # See https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-self-hosted-runners
      #
      # The value must be an escaped JSON string that will be decoded to the
      # jobs.runs-on field
      # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
      #
      # For example:
      # - A simple github runner: "\"ubuntu-22.04\""
      # - A list of labels: "[\"self-hosted\", \"linux\"]"
      # - A map: "{group: \"ubuntu-runners\", labels: \"ubuntu-20.04-16core\"}"
      runner:
        type: string
        default: '"ubuntu-latest"'
    secrets:
        PIPELINES_READ_TOKEN:
          required: true
env:
  PIPELINES_CLI_VERSION: v0.26.2-rc1
  PIPELINES_ACTIONS_VERSION: main

jobs:
  pipelines_drift_detection:
    name: Detect Infrastructure Drift
    runs-on: ${{ fromJSON(inputs.runner) }}
    steps:
      - name: Checkout Pipelines Actions
        uses: actions/checkout@v4
        with:
          path: pipelines-actions
          repository: gruntwork-io/pipelines-actions
          ref: ${{ env.PIPELINES_ACTIONS_VERSION }}
          token: ${{ secrets.PIPELINES_READ_TOKEN }}

      - name: Check out repo code
        uses: actions/checkout@v4
        with:
          path: infra-live-repo
          fetch-depth: 0

      - name: Cache Providers
        id: cache-providers
        uses: actions/cache@v4
        with:
          path: ~/.cache/terragrunt/providers
          key: ${{ runner.os }}-terragrunt-providers

      - name: Setup Mise Toml
        id: mise-toml
        working-directory: ./infra-live-repo
        shell: bash
        env:
          GENERATE_MISE_TOML: ${{ inputs.generate_mise_toml }}
          INFRA_LIVE_DIRECTORY: ${{ inputs.infra_live_directory }}
          TF_VERSION: ${{ inputs.tf_version }}
          TG_VERSION: ${{ inputs.tg_version }}
          TF_BINARY: ${{ inputs.tf_binary }}
        run: |
          if [[ ! -f ".mise.toml" ]]; then
            echo '::error::.mise.toml not found'
          else
            echo 'TOML<<EOF' >> "$GITHUB_OUTPUT"
            cat .mise.toml >> "$GITHUB_OUTPUT"
            echo '' >> "$GITHUB_OUTPUT"
            echo 'EOF' >> "$GITHUB_OUTPUT"
          fi

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          mise_toml: "${{ steps.mise-toml.outputs.TOML }}"

      - name: Test Terraform, OpenTofu and Terragrunt
        shell: bash
        run: |
          tofu --version || true
          terraform --version || true
          terragrunt --version

      - name: "Read in Gruntwork context"
        id: gruntwork_context
        uses: ./pipelines-actions/.github/actions/pipelines-bootstrap
        with:
          token: ${{ secrets.PIPELINES_READ_TOKEN }}
          branch: main

      - name: Load Machine User Name
        id: load_machine_user
        env:
          GH_TOKEN: ${{ secrets.PIPELINES_READ_TOKEN }}
        shell: bash
        run: |
          echo "MACHINE_USER_NAME=$(gh api /user | jq .login)" >> "$GITHUB_OUTPUT"

      - name: "Run terragrunt plan for all units"
        id: terragrunt
        working-directory: ./infra-live-repo
        env:
          GH_TOKEN: ${{ secrets.PIPELINES_READ_TOKEN }}
          MACHINE_USER_NAME: ${{ steps.load_machine_user.outputs.MACHINE_USER_NAME }}
          TERRAGRUNT_AUTH_PROVIDER_CMD: "pipelines auth terragrunt-credentials --ci github-actions --cloud aws --wd . --event-type pr-synched-created"
          TF_BINARY: ${{ steps.gruntwork_context.outputs.tf_binary }}
          INFRA_LIVE_REPO_BRANCH: ${{ steps.gruntwork_context.outputs.branch }}
          DEPLOY_BRANCH_NAME: ${{ steps.gruntwork_context.outputs.deploy_branch_name }}
          GRUNTWORK_CONFIG_FILE: ${{ steps.gruntwork_context.outputs.gruntwork_config_file }}
        shell: bash
        run: |
          if [ "$TF_BINARY" == "terraform" ]
          then
            export TERRAGRUNT_TFPATH=terraform
          else
            export TERRAGRUNT_TFPATH=tofu
          fi

          plan_folder="$(mktemp -d)"
          echo "plan_folder=$plan_folder" >> $GITHUB_OUTPUT

          # Find all units
          mapfile -t paths < <(find . -mindepth 2 -name "terragrunt.hcl" -exec dirname "{}" \;)
          for path in "${paths[@]}"; do
            echo "Running plan for $path"
            terragrunt_command="run-all plan --terragrunt-exclude-dir=. --terragrunt-include-dir=$path"
            pipelines execute terragrunt \
              --working-directory . \
              --infra-live-repo . \
              --infra-live-repo-branch "$INFRA_LIVE_REPO_BRANCH" \
              --deployment-branch "$DEPLOY_BRANCH_NAME" \
              --gruntwork-config-file "$GRUNTWORK_CONFIG_FILE" \
              --out-dir "$plan_folder" \
              --command "$terragrunt_command"
          done

      - name: Clean repo
        id: clean-repo
        working-directory: ./infra-live-repo
        shell: bash
        run: |
          # Remove any unwanted files created during planning
          git clean -f -f -d -x
          git reset --hard
      
      - name: "Parse plans"
        id: tfplan
        working-directory: ./infra-live-repo
        shell: bash
        env:
          WORKING_DIRECTORY: ${{ steps.gruntwork_context.outputs.working_directory }}
          GH_TOKEN: ${{ github.token }}
          PLAN_FOLDER: ${{ steps.terragrunt.outputs.plan_folder}}
        run: |
          pipelines tfplan detect-drift --working-directory "$WORKING_DIRECTORY" "$PLAN_FOLDER"
      
      - name: "Create PR"
        id: propose-infra-change
        working-directory: ./infra-live-repo
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          WORKING_DIRECTORY: ${{ steps.gruntwork_context.outputs.working_directory }}
          BRANCH_NAME: "drift-detection"
          AUTHOR_NAME: ${{ github.actor }}
          AUTHOR_EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          
        run: |
          git_changes=$(git status --porcelain)
          if [[ -n $git_changes ]]; then
            pipelines scm propose-infra-change \
              --working-directory "$WORKING_DIRECTORY" \
              --change-request-branch-name "$BRANCH_NAME" \
              --commit-message "Drift Detected" \
              --title "Drift Detected" \
              --author-name "$AUTHOR_NAME" \
              --author-email "$AUTHOR_EMAIL" \
              --force true
          fi

