name: Pipelines
run-name: Drift Detection
on:
  workflow_call:
    inputs:
      # This field can be overriden to customize the runner used for pipelines
      # workflows.
      #
      # IMPORTANT: To use self-hosted runners this workflow must be hosted in
      # the same GitHub organization as your infra-live repository.
      # See https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-self-hosted-runners
      #
      # The value must be an escaped JSON string that will be decoded to the
      # jobs.runs-on field
      # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
      #
      # For example:
      # - A simple github runner: "\"ubuntu-22.04\""
      # - A list of labels: "[\"self-hosted\", \"linux\"]"
      # - A map: "{group: \"ubuntu-runners\", labels: \"ubuntu-20.04-16core\"}"
      runner:
        type: string
        default: '"ubuntu-latest"'
    secrets:
        PIPELINES_READ_TOKEN:
          required: true
        INFRA_ROOT_WRITE_TOKEN:
          required: true
env:
  PIPELINES_CLI_VERSION: v0.28.0-rc5
  PIPELINES_ACTIONS_VERSION: 2024-07-19_get-job-id

jobs:
  determine_units:
    name: Detect Infrastructure Drift
    runs-on: ${{ fromJSON(inputs.runner) }}
    outputs:
      units: ${{ steps.determine-units.outputs.units }}
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
        with:
          path: infra-live-repo
          fetch-depth: 0

      - name: Determine Units
        id: determine-units
        working-directory: ./infra-live-repo
        shell: bash
        run: |
          mapfile -t paths < <(find . -mindepth 2 -name "terragrunt.hcl" -exec dirname "{}" \;)
          # debug - limit to first 10
          paths=("${paths[@]:0:10}")
          echo "units<<EOF" >> "$GITHUB_OUTPUT"
          # Initialize the JSON array
          json="["

          # Loop through the paths array and construct JSON objects
          for i in "${!paths[@]}"; do
              json+="{\"id\": $i, \"path\": \"${paths[$i]#./}\"},"
          done

          # Remove the trailing comma and close the JSON array
          json="${json%,}]"

          echo "$json" >> "$GITHUB_OUTPUT"
          echo "" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  pipelines_drift_detection:
    runs-on: ${{ fromJSON(inputs.runner) }}
    needs: determine_units
    strategy:
      matrix:
        unit: ${{ fromJSON(needs.determine_units.outputs.units) }}
    env:
      JOB_NAME: Detect Drift in ${{ matrix.unit.path }}
    name: Detect Drift in ${{ matrix.unit.path }}
    steps:
      - name: Checkout Pipelines Actions
        uses: actions/checkout@v4
        with:
          path: pipelines-actions
          repository: gruntwork-io/pipelines-actions
          ref: ${{ env.PIPELINES_ACTIONS_VERSION }}
          token: ${{ secrets.PIPELINES_READ_TOKEN }}

      - name: Check out repo code
        uses: actions/checkout@v4
        with:
          path: infra-live-repo
          fetch-depth: 0

      - name: Setup Mise Toml
        id: mise-toml
        working-directory: ./infra-live-repo
        shell: bash
        env:
          GENERATE_MISE_TOML: ${{ inputs.generate_mise_toml }}
          INFRA_LIVE_DIRECTORY: ${{ inputs.infra_live_directory }}
          TF_VERSION: ${{ inputs.tf_version }}
          TG_VERSION: ${{ inputs.tg_version }}
          TF_BINARY: ${{ inputs.tf_binary }}
        run: |
          if [[ ! -f ".mise.toml" ]]; then
            echo '::error::.mise.toml not found'
          else
            echo 'TOML<<EOF' >> "$GITHUB_OUTPUT"
            cat .mise.toml >> "$GITHUB_OUTPUT"
            echo '' >> "$GITHUB_OUTPUT"
            echo 'EOF' >> "$GITHUB_OUTPUT"
          fi

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          mise_toml: "${{ steps.mise-toml.outputs.TOML }}"

      - name: Test Terraform, OpenTofu and Terragrunt
        shell: bash
        run: |
          tofu --version || true
          terraform --version || true
          terragrunt --version

      - name: "Read in Gruntwork context"
        id: gruntwork_context
        uses: ./pipelines-actions/.github/actions/pipelines-bootstrap
        with:
          token: ${{ secrets.PIPELINES_READ_TOKEN }}
          branch: main

      - name: Load Machine User Name
        id: load_machine_user
        env:
          GH_TOKEN: ${{ secrets.PIPELINES_READ_TOKEN }}
        shell: bash
        run: |
          echo "MACHINE_USER_NAME=$(gh api /user | jq .login)" >> "$GITHUB_OUTPUT"

      - name: "Run terragrunt plan"
        id: terragrunt
        working-directory: ./infra-live-repo
        env:
          GH_TOKEN: ${{ secrets.PIPELINES_READ_TOKEN }}
          MACHINE_USER_NAME: ${{ steps.load_machine_user.outputs.MACHINE_USER_NAME }}
          TERRAGRUNT_AUTH_PROVIDER_CMD: "pipelines auth terragrunt-credentials --ci github-actions --cloud aws --wd . --event-type pr-synched-created"
          TF_BINARY: ${{ steps.gruntwork_context.outputs.tf_binary }}
          INFRA_LIVE_REPO_BRANCH: ${{ steps.gruntwork_context.outputs.branch }}
          DEPLOY_BRANCH_NAME: ${{ steps.gruntwork_context.outputs.deploy_branch_name }}
          GRUNTWORK_CONFIG_FILE: ${{ steps.gruntwork_context.outputs.gruntwork_config_file }}
          UNIT_PATH: ${{ matrix.unit.path }}
        shell: bash
        run: |
          set -euo pipefail
          if [ "$TF_BINARY" == "terraform" ]
          then
            export TERRAGRUNT_TFPATH=terraform
          else
            export TERRAGRUNT_TFPATH=tofu
          fi

          root_plan_folder="$(mktemp -d)"
          echo "root_plan_folder=$root_plan_folder" >> $GITHUB_OUTPUT

          echo "Running plan for $UNIT_PATH"
          terragrunt_command="plan"
          plan_folder="$root_plan_folder/${UNIT_PATH}"
          mkdir -p "$plan_folder"

          stderr_log='/tmp/pipelines-stderr.log'

          set +e
          pipelines execute terragrunt \
            --working-directory "$UNIT_PATH" \
            --infra-live-repo . \
            --infra-live-repo-branch "$INFRA_LIVE_REPO_BRANCH" \
            --deployment-branch "$DEPLOY_BRANCH_NAME" \
            --gruntwork-config-file "$GRUNTWORK_CONFIG_FILE" \
            --out-dir "$plan_folder"  \
            --command "$terragrunt_command" 2>&1 | tee "$stderr_log"
          pipelines_exit_code=$?
          set -e

          error_excerpt=$(cat "$stderr_log" | awk 'BEGIN {IGNORECASE=1} /error/{print; found=1} found && NR<=10 {print; next}')
          # Strip ANSI color codes
          cleaned_error_excerpt=$(echo "$error_excerpt" | sed 's/\x1b\[[0-9;]*m//g')
          echo 'error_excerpt<<EOF' >> "$GITHUB_OUTPUT"
          echo "$cleaned_error_excerpt" >> $GITHUB_OUTPUT
          echo '' >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"

          echo "pipelines_exit_code=$pipelines_exit_code" >> $GITHUB_OUTPUT 
          if [[ $pipelines_exit_code -ne 0 ]]; then
            echo "::error::Error running plan for $UNIT_PATH"
          fi

      - name: "Parse plans"
        id: tfplan
        if: steps.terragrunt.outputs.pipelines_exit_code == 0
        working-directory: ./infra-live-repo
        shell: bash
        env:
          WORKING_DIRECTORY: ${{ steps.gruntwork_context.outputs.working_directory }}
          PLAN_FOLDER: ${{ steps.terragrunt.outputs.root_plan_folder}}
        run: |
          pipelines tfplan detect-drift --working-directory "$WORKING_DIRECTORY" "$PLAN_FOLDER"
      
      - name: Get Logs URL
        id: get_logs_url
        uses: ./pipelines-actions/.github/actions/pipelines-get-job-logs-url
        with:
          job_name: ${{ env.JOB_NAME }}
          step_name_prefix: "Run terragrunt plan"

      - name: "Capture output"
        id: capture-result
        working-directory: ./infra-live-repo
        shell: bash
        env:
          PIPELINES_EXIT_CODE: ${{ steps.terragrunt.outputs.pipelines_exit_code }}
          UNIT_PATH: ${{ matrix.unit.path }}
          ID: ${{ matrix.unit.id }}
          LOGS_URL: ${{ steps.get_logs_url.outputs.step_logs_url }}
          ERROR_EXCERPT: ${{ steps.terragrunt.outputs.error_excerpt }}
        run: |
          cd "$UNIT_PATH"
          if [[ $PIPELINES_EXIT_CODE -ne 0 ]]; then
            jq -n --arg path "$UNIT_PATH" --arg logs_url "$LOGS_URL" --arg error_excerpt "$ERROR_EXCERPT" '{"path": $path, "error": true, "logs_url": $logs_url, "error_excerpt": $error_excerpt}' > result-"$ID".json
          elif git status --porcelain | grep -q ".drift-history.json"; then
            last_line=$(tail -n 1 .drift-history.json | jq -R '.')
            jq -n --arg path "$UNIT_PATH" --arg drift "$last_line" '{"path": $path, "drift": $drift}' > result-"$ID".json
          fi

      - name: "Upload result"
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.unit.id }}
          path: infra-live-repo/${{ matrix.unit.path }}/result-${{ matrix.unit.id }}.json
          if-no-files-found: ignore
          retention-days: 1
          overwrite: true

  consolidate_jobs:
    runs-on: ${{ fromJSON(inputs.runner) }}
    needs: pipelines_drift_detection
    steps:
      - name: Checkout Pipelines Actions
        uses: actions/checkout@v4
        with:
          path: pipelines-actions
          repository: gruntwork-io/pipelines-actions
          ref: ${{ env.PIPELINES_ACTIONS_VERSION }}
          token: ${{ secrets.PIPELINES_READ_TOKEN }}

      - name: Check out repo code
        uses: actions/checkout@v4
        with:
          path: infra-live-repo
          fetch-depth: 0

      - name: Install Pipelines CLI
        uses: ./pipelines-actions/.github/actions/pipelines-install
        with:
          version: ${{ env.PIPELINES_CLI_VERSION }}
          token: ${{ secrets.PIPELINES_READ_TOKEN }}

      - name: "Download results"
        uses: actions/download-artifact@v4
        with:
          pattern: result-*
          path: results
          merge-multiple: true

      - name: "Extract results"
        id: extract-results
        shell: bash
        run: |
          ls -R results
          drifted_paths=()
          error_paths=()
          error_urls=()
          error_excerpts=()
          for result in results/*.json; do
            path=$(jq -r '.path' "$result")
            has_error=$(jq -r '.error' "$result")
            logs_url=$(jq -r '.logs_url' "$result")
            error_excerpt=$(jq -r '.error_excerpt' "$result")
            if [ "$has_error" = "true" ]; then
              # Add the path to the array of error paths
              error_paths+=("$path")
              error_urls+=("$logs_url")
              error_excerpts+=("$error_excerpt")
            else
              drifted_paths+=("$path")
              # Extract the 'drift' value
              drift=$(jq -r '.drift' "$result")
              # Append the drift to the .drift-history.json file at the specified path
              echo "$drift" | jq -c '. | fromjson' >> "./infra-live-repo/$path/.drift-history.json"
            fi
          done

          drifted_paths_markdown=""
          if [ ${#drifted_paths[@]} -ne 0 ]; then
            drifted_paths_markdown+="## ${#drifted_paths[@]} Drifted Units:\n"
            for path in "${drifted_paths[@]}"; do
              drifted_paths_markdown+="- <code>$path</code>\n"
            done
            drifted_paths_markdown+="\n"

            drifted_paths_markdown+="1. Gruntwork Pipelines will automatically run a <code>plan</code> showing all changes needed to resolve the drift.\n"
            branch_link="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/drift-detection"
            drifted_paths_markdown+="1. Optionally push commits to [this branch]($branch_link) to bring your IaC into alignment with currently deployed resources.\n"
            drifted_paths_markdown+="3. Merge this pull request to <code>apply</code> the changes and resolve the drift.\n"

            echo "drifted_paths_markdown=$drifted_paths_markdown" >> "$GITHUB_OUTPUT"
          fi

          errored_paths_markdown=""
          if [ ${#error_paths[@]} -ne 0 ]; then
            errored_paths_markdown+="## :warning: ${#error_paths[@]} Unscanned Units:\n"
            errored_paths_markdown+="Drift detection was not performed for these units because the plans failed:\n"
            for i in "${!error_paths[@]}"; do
              path="${error_paths[$i]}"
              logs_url="${error_urls[$i]}"
              error_excerpt="${error_excerpts[$i]}"
              errored_paths_markdown+="<details><summary><code>$path</code></summary>\n\n"
              errored_paths_markdown+="\`\`\`terraform\n"
              errored_paths_markdown+=${error_excerpt//$'\n'/\\n}
              errored_paths_markdown+="\n"
              errored_paths_markdown+="\`\`\`\n"
              errored_paths_markdown+="[View logs]($logs_url)\n"
              errored_paths_markdown+="</details>\n"
            done
            echo "errored_paths_markdown=$errored_paths_markdown" >> "$GITHUB_OUTPUT"
          fi

      - name: "Create PR"
        id: propose-infra-change
        working-directory: ./infra-live-repo
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.INFRA_ROOT_WRITE_TOKEN }}
          WORKING_DIRECTORY: .
          BRANCH_NAME: "drift-detection"
          AUTHOR_NAME: ${{ github.actor }}
          AUTHOR_EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          DRIFTED_PATHS_MARKDOWN: ${{ steps.extract-results.outputs.drifted_paths_markdown }}
          ERRORED_PATHS_MARKDOWN: ${{ steps.extract-results.outputs.errored_paths_markdown }}
        run: |
          git_changes=$(git status --porcelain)
          if [[ -n $git_changes ]]; then
            logs_url="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
            body="# :left_right_arrow: Drift Detected\n"
            body+="This pull request remediates [detected drift]($logs_url) between IaC in this repository and cloud resources in AWS.\n"
            body+="\n"
            body+="$DRIFTED_PATHS_MARKDOWN\n"
            body+="$ERRORED_PATHS_MARKDOWN\n"
            escaped_body=$(echo -e "$body")

            echo "$escaped_body"

            pipelines scm propose-infra-change \
              --working-directory "$WORKING_DIRECTORY" \
              --change-request-branch-name "$BRANCH_NAME" \
              --commit-message "Drift Detected" \
              --title "Drift Detected" \
              --body "$escaped_body" \
              --author-name "$AUTHOR_NAME" \
              --author-email "$AUTHOR_EMAIL" \
              --force true
          fi

      - name: "Show Pull Request URL in Summary"
        shell: bash
        if: ${{ steps.propose-infra-change.outputs.pipelines_change_request_url }}
        env:
          PR_URL: ${{ steps.propose-infra-change.outputs.pipelines_change_request_url }}
        run: |
          echo "### ↔️ Drift Detected" >> "$GITHUB_STEP_SUMMARY"
          echo "[Link to Drift Remediation Pull Request]($PR_URL)" >> "$GITHUB_STEP_SUMMARY"
